apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-eksternt-api
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  ingresses:
    - https://arbeidssoekerperioder.ekstern.dev.nav.no
  port: 8080
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "arbeidssokerregisteret.read"
          enabled: true
          product: "arbeid"
          allowedIntegrations:
            - maskinporten
          atMaxAge: 120
          consumers:
            - name: "NAV"
              orgno: "889640782"
            - name: "Statens lånekassen for utdanning"
              orgno: "960885406"
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: arbeidssoekerregisteretapiekstern
